// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9ZUfU3cnt_38ShLb9nGpRWTPxE6YFk1s',
    appId: '1:769139252463:web:746784b4c18b6ca23ecf1a',
    messagingSenderId: '769139252463',
    projectId: 'invent-ory-app',
    authDomain: 'invent-ory-app.firebaseapp.com',
    storageBucket: 'invent-ory-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7h_soZ7UpTKMRA1-nt2uUVep116pj_xM',
    appId: '1:769139252463:android:e79a93e32e8594433ecf1a',
    messagingSenderId: '769139252463',
    projectId: 'invent-ory-app',
    storageBucket: 'invent-ory-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxmverwx1tx25cEtXb21rhMjGeQUjnD-8',
    appId: '1:769139252463:ios:f1a5ab7737ce03453ecf1a',
    messagingSenderId: '769139252463',
    projectId: 'invent-ory-app',
    storageBucket: 'invent-ory-app.appspot.com',
    iosClientId: '769139252463-2lq02vvmk564gcmhv5bfrtu6hm3gm29e.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxmverwx1tx25cEtXb21rhMjGeQUjnD-8',
    appId: '1:769139252463:ios:f1a5ab7737ce03453ecf1a',
    messagingSenderId: '769139252463',
    projectId: 'invent-ory-app',
    storageBucket: 'invent-ory-app.appspot.com',
    iosClientId: '769139252463-2lq02vvmk564gcmhv5bfrtu6hm3gm29e.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventory',
  );
}
